### ISSUE TITLE
div.usa-nav-secondary blocking primary nav element (Manage life changes)

### ISSUE THREAD

**Issue by chachi69** [frtib/tsp-redesign#44] opened 2018-07-28 21:51 UTC
`div.usa-nav-secondary` is blocking right-most primary nav element (Manage life changes) because it is sizing itself to accommodate the login form,  even with visibility: hidden. The login form probably needs to be decoupled from `div.usa-nav-secondary`.

![login-form](https://user-images.githubusercontent.com/9728434/43360874-69a7d950-928e-11e8-9dbc-a39134f4c661.png)

**Comment by line47** [comment] 2018-07-30 15:59
@chachi69 I fixed this in PR #43 👍 Just ready to be merged now

**Comment by chachi69** [comment] 2018-07-30 17:55
There are z-index issues with the login form — they were a headache when I originally developed this too. Removing the login form from `div.usa-nav-secondary` is one approach, but if we set the form to `visibility: hidden` and `left: 1000px`, that should prevent `div.usa-nav-secondary` from blocking the primary nav. I just experimented with this for a separate issue on the legacy site. 
https://codepen.io/dferracci/pen/pZdmjE

![login-z](https://user-images.githubusercontent.com/9728434/43413958-73c4131e-93ff-11e8-9844-a210a9a82721.png)

**Comment by line47** [comment] 2018-07-30 18:17
Ccn you open this is a separate issue? @chachi69

**Comment by chachi69** [comment] 2018-07-30 18:42
Certainly. I saw the [Reopen issue] button and went for it. Is there a best
practice for reopening vs. creating new issues?

**Closed** 2018-07-30 18:52 UTC

**Comment by line47** [comment] 2018-07-30 19:05
I follow thee guidelines

- `Reopen` if the issue is not fixed. 
- `New issue` if the issue is new and for a different item.

In this example here, one was bout the navigation and the other was about `div.usa-nav-secondary blocking primary nav element ` and the new one is regarding the modal pop up.
